### ISSUE TITLE
[dashboard]: when searching "fire" and firefox shows up as icon below, one cannot simply hit "enter" to start it

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#12]
when searching in dashboard, it would be nice when at any time one could start navigating with the arrow-keys inside the results list and/or hit enter to launch the highlighted item

**Comment by eikehein** [comment]
This is some sort of regression, obviously this is supposed to work (and used to) - looking into it ...

**Comment by star-buck** [comment]
its odd: it seems to not work only with certain apps, like "firefox" or "yakuake".
It work with "konsole" though, so I am not sure why it sometimes renders in a state, where the remaining icon seems only visually active but doesnt have real focus?

**Comment by eikehein** [comment]
It's likely related to the changes https://quickgit.kde.org/?p=plasma-desktop.git&a=commit&h=78b4096044fd8e125e5170f00eb5eb1944a2e4a4

**Comment by eikehein** [comment]
It's a race condition between the (hidden) search field receiving keyboard focus due to input events and the multi-grid view grabbing focus due to runner results changing - whether it happens depends a bit on the speed of the runner results coming in which is why I didn't catch it originally. I'll have to think a bit about how to change the event routing and will fix it tomorrow :)

**Comment by eikehein** [comment]
Fixed by https://quickgit.kde.org/?p=plasma-desktop.git&a=commit&h=8d534f94a6de944dd2f99a1b0f0026933f56c5bd

**Comment by star-buck** [comment]
@eikehein :
please mark things fixed with green label, also mention version which should have the fix officially shipped, thanks.

**Comment by eikehein** [comment]
Sorry! I was on a mobile device and can never find the label stuff in the mobile GitHub UI.

Target versions are v5.5.4 (if the release team makes one) or v5.6

While this fixes the problem for now I'm still not really happy with the way the keyboard event handling code works internally and will probably rewrite it a third time for performance reasons soon (it's OK for now though). The reason this is surprisingly tricky is that nothing is really designed with the idea of having a hidden text field in mind that can always be typed into and doesn't interfere with arrow nav - but I'm really attached to that design aesthetically. It's solvable but needs more elaborate code for perfection.
